Temasys/AdapterJS

- source/adapter.js
Close plugin install banner only when the user clicks on Cancel, as opposed to the current behaviour, which is closing the banner any time the user clicks anywhere on the banner.
Incidentally this lets the user actually click on the link to the plugin portal.
> TWP-275 Close plugin install banner only when the user clicks on Cancel

- source/adapter.js
@letchoo 
We had feedbacks informing us that the <video> sizes weren't copied properly when the element was hidden of in a hidden div:
Scenario:
- have a <video> element in a hidden <div>
- set the <video> element's size to 800x600px
- attachMediaStream on it
- unhide the div
Expected:
- the plugin <object> is 800x600px
Observed:
- the plugin <object> is 0x0px
I think this should fix the issue.
clientWith and clientHeight are computed values, so when the element is hidden, they have a value of 0.
> AJS-231: changed <video> size copy strategy to support hidden elements

- tests/unit/Plugin.object.stability.spec.js
This test pops plugin <object> in and out of the DOM.
This is to check for crashes when objects are added and remove to often.
> AJS-230 added test to pop plugin <object> in and out of the DOM

- Gruntfile.js
- package.json
- source/adapter.js
- source/pluginInfo.js
This is so that the plugin config can be changed very easily (see JIRA)
* Removed the pluginInfo from AJS
* Moved it to a separate file
* compiling both on grunt publish
!!! This means that one cannot use source/adapter.js directly but has to use the compiled version !!!
> Ajs 227 AdapterJS generation

- source/adapter.js
stream::enableSoundTrack is deprecated starting on plugin verion 0.8.862.
Call it only when it is defined in prevision of the function being removed.
> AJS-237 call enableSoundTracks only when defined.

- Gruntfile.js
- source/adapter.js
Content:
- Refactor of AdapterJS.parseWebrtcDetectedBrowser in simpler, cleaner
- Call if AdapterJS.parseWebrtcDetectedBrowser after import of Google's adapter to set webrtcDetectedType
- for the plugin, webrtcDetectedVersion is now set to the browser version, not to the plugin's. 
Use AdapterJS.WebRTCPlugin.plugin.VERSION to get the plugin version
> Issue 152 - webrtc detected type missing

- source/adapter.js
FF43+ prints warnings when the ice candidates url in in a 'url' element.
Use 'urls' instead.
Also, printing a warning when createIceServer(s) is call, notifying the user that the functions are set to be deprecated.
> AJS-242 createiceserver throws warnings on ff43

- source/adapter.js
- tests/unit/RTCPeerConnection.constraints.spec.js
The next plugin version supports a new constructor more in line with the specs
https://www.w3.org/TR/webrtc/#widl-ctor-RTCPeerConnection--RTCConfiguration-configuration
This 
* calls the new constructor if it is available, 
* call the previous constructor otherwise
> TWP-396: Splitting new and old constructors for RTCPeerConnection

- source/adapter.screenshare.js
This PR commits should:
- Fix the prompt that is not prompting
- Removal of the auto-generation of Firefox extension link and link to a default Skylink extension link. This might take about 10days for full-review to be verified, but link is still the same and usable.
> Fixes for Firefox screensharing addon

- Gruntfile.js
- source/adapter.js
When imported in global scope (say, directly in a script tag), the existing code works fine because `window.getUserMedia = ...` also assigns to the `getUserMedia` variable declared as part of the included google adapter.js code.
However, when the code isn't imported in global scope (for example, if it's included via webpack - where it's evaluated inside a function), `window.getUserMedia` and `getUserMedia` are actually two different variables.  This causes `requestUserMedia` (defined in the google adapter.js code) to fail when it tries to read the local `getUserMedia` variable, which will be null at this point.
I can add a commit to update the stuff in `publish` (calling `grunt publish` after initializing the submodule), if you want.
> Fix getUserMedia when not imported in global scope (ex. via webpack)

- source/adapter.js
In answer of https://github.com/Temasys/AdapterJS/issues/177 .
Setting `srcObject` to `null` on a video object generates an error on Chrome.
Create a special case for Chrome where we set it to an empty string instead.
> github#177 special case for attachMediaStream on Chrome when no stream

- source/adapter.js
Tested in `http:` protocol environment compiled with browserify using SkylinkJS test scripts compilation.
I followed the logic @johache had to resolve PR #173 fixes.
----
**(PASS) Firefox 45**
- `webrtcDetectedBrowser` -> `"firefox"`
- `webrtcDetectedVersion` -> `45`
- `webrtcMinimumVersion` -> `31`
**(PASS) Chrome 49**
- `webrtcDetectedBrowser` -> `"chrome"`
- `webrtcDetectedVersion` -> `49`
- `webrtcMinimumVersion` -> `38`
**(PASS) Safari 8.0.6**
- `webrtcDetectedBrowser` -> `"safari"`
- `webrtcDetectedVersion` -> `8`
- `webrtcMinimumVersion` -> `7`
**(PASS) Opera 35**
- `webrtcDetectedBrowser` -> `"opera"`
- `webrtcDetectedVersion` -> `35`
- `webrtcMinimumVersion` -> `26`
**(PASS) Firefox 45**
- `webrtcDetectedBrowser` -> `"firefox"`
- `webrtcDetectedVersion` -> `45`
- …
> AJS-253: Fixes for undefined webrtcDetectedBrowser, webrtcDetectedVersion and webrtcMinimumVersion using browserify

- source/adapter.js
- source/adapter.screenshare.js
Re-opened from #184 due to incorrect branch.
----
This should fix the issue in IE browsers that navigator.mediaDevices is not defined.
See JIRA Ticket - [AJS-257](http://jira.temasys.com.sg/browse/AJS-257)
> AJS-257: Fixes to ensure that navigator.mediaDevices is always defined.

- source/adapter.js
> NOTE: Still requiring testing
This commit simply copies logic for both new and old format of constructing the plugin `RTCPeerConnection` object.
> TWP-443: Fixes to ensure "relay" candidates are returned if TURN credentials are provided

- source/adapter.js
MediaStreamTrack is implemented by the browsers as an instance of function (with prototype), the current polyfill implementation as an object make this kind of check raise an error:
```
window.MediaStreamTrack  && 'aMethod' in window.MediaStreamTrack.prototype
```
> change MediaStreamTrack from Object to Function type.

- source/adapter.js
As informed before, this fixes aims to:
- Resolve the issues that the [`attachMediaStream` API for `webkitGetUserMedia` detection](https://github.com/Temasys/AdapterJS/blob/0.13.3/publish/adapter.debug.js#L1054) that might not work for Opera browsers since their implementation of Chromium is not the same as the browser version.
PS: Ignore the whitespaces removal changes in this commit. These lines aren't actually really changed but my sublime plugin helps me remove unwanted spaces. The changes begins from [here](https://github.com/Temasys/AdapterJS/pull/214/commits/3ade793b48474ed42748b941d8cb2ab1cedf9945#diff-b1ee9bbe2f0ee05f1717e6f3fe0187d7R681).
> AJS-274: Fixes for attachMediaStream API in Opera 39+ browsers

- source/adapter.js
This fixes the issue:
> WebRTC interfaces with the "moz" prefix (mozRTCPeerConnection, mozRTCSessionDescription, mozRTCIceCandidate) have been deprecated.
Since in [`webrtc/adapter` line](https://github.com/webrtc/adapter/blob/v2.0.3/src/js/firefox/firefox_shim.js#L65) it checks if the undeprecated `RTCPeerConnection` API exists before shimming it, but [in this line](https://github.com/Temasys/AdapterJS/blob/0.14.0/source/adapter.js#L579), we define the interfaces as `null` again, hence making `webrtc/adapter` code to polyfill it although it has been deprecated.
> AJS-278: Handle deprecation for "moz" interfaces correctly.

- source/pluginInfo.js
From https://github.com/Temasys/AdapterJS/issues/229
"replace links like http://skylink.io/plugin/, http://bit.ly/webrtcpluginpkg, http://bit.ly/webrtcpluginmsi with https versions."
> github#229 HTTPS links

- source/adapter.screenshare.js
when the screensharing extension in not available, FF now seems to return a ``NotAllowedError`` instead of ``PermissionDeniedError`` or ``SecurityError``.
Just add the former to the list of expected errors when the extension is not available.
> github#226: added support for NotAllowedError on FF 

- README.md
- source/adapter.js
- source/adapter.screenshare.js
This commit contains:
- Fixes for the change from "SecurityError" to "NotAllowedError" as defined in this [bugzilla ticket here](https://bugzilla.mozilla.org/show_bug.cgi?id=1257950).
- Bump to Firefox min version `33` as Firefox browser screensharing is only supported from that version onwards.
> Firefox add-on is not triggered due to Error name change from "SecurityError" to "NotAllowedError"

- README.md
It seems like bowser (current latest version is `0.6.1`) does not work with iOS 10+. Tested and seems like it only works on iOS 9+.
See the related ticket: [EricssonResearch/bowser#97](https://github.com/EricssonResearch/bowser/issues/97)
> Update bowser support on README

- source/adapter.js
- source/adapter.screenshare.js
**What is the issue:**
When clicking on a button on a rendered notification bar that is on non-plugin browsers (chrome/firefox/opera), the "isIE is not defined" error throws. This is likely that "isIE" variable is only defined when case is plugin browser.
**How to reproduce it:**
- Go to a chrome/firefox/opera browser (non-plugin supported browser)
- Access any plugin demo. E.g.: https://plugin.temasys.com.sg/demo/src/content/peerconnection/trickle-ice/
- Key in this notification bar rendering to stimulate triggering for requiring add-on installation: AdapterJS.renderNotificationBar('install message', 'clickforerror', window.location.href, false, false);
- Click the "clickforerror" button
- Notice that "isIE" not defined error throws 
----
This PR aims to prevent the error from throwing …
> AJS-250: Fixes for "isIE" undefined error throwing when clicking button on notification bar

- Gruntfile.js
- package.json
- source/adapter.js
- source/adapter.screenshare.js
This should fix #238 for now.
Currently while we look into make AdapterJS handle the browserify issues with webrtc/adapter dependency when we have the time, this temp fixes if it doesn't cause any issues should resolve the issue:
- Replace the `require(` to `requirecopy(` in the browserified file.
- Since `AdapterJS.webRTCReady()` is required initialization method to be invoked, define the screensharing overrides if requirejs module is defined.
Tested on:
- SkylinkJS tape tests which has the `require("./utils")` not found error and it works.
- SkylinkJS demo that doesn't use requirejs and it works.
- SkylinkJS getaroom.io demo and it works, the screensharing polyfills were called.
> AJS-283: Temp files for require("./utils") not found and requirejs async calls in webrtc/adapterjs browserified dependency

- README.md
- source/adapter.js
- source/adapter.screenshare.js
> **Note**: <s>New extensions must be approved first, and then the ID and links can be updated to this branch before this PR can be merged. Additionally</s> this blocks the release of [ESS-886](https://jira.temasys.com.sg/browse/ESS-886) since it is tested with this branch.
This PR is to patch Chrome/IE/Safari `"mediaSource"` flag not being honoured, and realised that an entire extension update has to be done. This is for us to ensure our polyfills and extensions are up-to-date as of what's the current state of things in implementations. This PR might have huge code changes.
Note that we are not waiting for the extensions to be approved due to time constraints, that will be another mini PR for that.
- Added `AdapterJS.extensionInfo` object to allow configuration of custom extension using …
> AJS-261: Extensions upgrade and allowing configuration of extensions from AdapterJS level

- source/adapter.js
- The latest version of `webrtc/adapter` uses the ORTC polyfill still, which doesn't work on the latest Edge browsers on Windows Creator Update. Since RTCPeerConnection API is available, there's no need for polyfills.
- This should prevent any overrides from the `webrtc/adapter`.
> Use native RTCPeerConnection API when available for Edge browsers on Windows Creator Update

- source/adapter.js
Everything is in the title...
This change doesn't actually have any impact at the moment as we still set optional[n].sourceId, but eventually, we want to move away from this system.
> AJS-284 prevent filtering of mediaSource in contraintsToPlugin

- source/adapter.js
In very slow networks, waiting for ```document.readyState``` to move to ```'complete'``` might take a long time (seconds, minutes).
When the readystate is ```'interactive'```, the DOM is ready and the plugin should be able to start.
> TWP-721 Allow document.readystate interative

- source/adapter.js
**Some improvements:**
- Remove redundant `"isIE"` flag with the `AdapterJS.webrtcDetectedBrowser` to pollute global scope less.
- Define `requestUserMedia` is scope for documentation purposes and clarity.
- Polyfill `getUserMedia()` and `navigator.getUserMedia()` for Safari 11.
> Remove redundant "isIE" flag

- source/adapter.screenshare.js
This resolves the issue where `getUserMedia({ video: { mediaSource: "screen" } })` for chrome as it listens to all messages in the same page. Currently in the deprecated method which some apps would still be using, the extension would listen to messages from `window.postMessage()` and react upon it. That however is a current problem in the AdapterJS since it is listening to all messages instead of acting upon specific messages, and that causes issues for JS plugins that are using the `window.postMessage()` as well. 
The current PR just simply listens for specific messages instead.
> AJS-293: Prevent listening to messages that does not come from self to extension

- source/adapter.js
Waiting on customer validation in this ticket https://jira.temasys.com.sg/browse/TWP-759
In the meantime, I just want your pre-approval of the changes, so that I can merge asap.
Logic implemented : we support document.readyState==='interactive', on all browsers but IE < 11. Set the flag AdapterJS.options.alwaysAllowInteractiveState to true, to enable document.readyState==='interactive' on IE < 11
> Twp 759 document.readyState==='interactive' IE 10

- source/adapter.js
**Purpose of this PR**
In situations where navigator.mimeTypes are not available (headless browsers), the AJS code needs to make a safe check and display plugin not supported banner.
> Added check for navigator.mimeTypes undefined. Should show plugin not supported banner
